services: 
  # db:
  #   image: postgres:14-alpine
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: "my-secret-pw"
  #     POSTGRES_DB: "my_database"
  #   volumes:
  #     - ./db:/docker-entrypoint-initdb.d
  #     - db-data:/var/lib/postgresql/data
    
  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      # DATABASE_URL: postgres://postgres:my-secret-pw@db:5432/my_database
      DATABASE_URL: ${POSTGRES_DB} # Skriv in POSTGRES_DB=postgres:// i .env fil.
    # depends_on:
    #   - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api

# volumes:
#   db-data: